#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379

#log
logging:
  config: classpath:logback-spring.xml
  path: /logs/${spring.application.name}
spring:
  #rabbitmq
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
  #redis
  redisson:
    address: 127.0.0.1:6379
  #kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: vote-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
